language: cpp
sudo: false
dist: trusty
compiler:
  - gcc
addons:
  apt:
    packages:
      - cmake
      - make
      - libqt4-dev
before_script:
  - mkdir build
  - cd build
  - cmake -DQJSON_BUILD_TESTS=yes ..
script:
  - make
  - make test
